### ISSUE TITLE
peers.dat inclusion in .gitignore?

### ISSUE THREAD

**Issue by etree** [taperj/aprcoin-tor#1]
Is peers.dat something you want to be tracking in git? I would assume it is constantly changing and would be outside of version control? Perhaps you are doing that intentionally and seeding peers?

**Comment by taperj** [comment]
> Is peers.dat something you want to be tracking in git? I would assume it is constantly changing and would be outside of version control? Perhaps you are doing that intentionally and seeding peers?

You are correct and I debated whether to include it or not. Really I included it because the initial installer I looked at from the APR website had included it. I went back and forth on it also, being a constantly changing file as  you stated. I figured it was better to leave it included and avoid syncing problems from peers who possibly couldn't find a block source. Your point is valid and well taken though and I may cut it out of inclusion in future releases. I'd just want to do the testing to make sure it doesn't end with stuck clients unable to sync if removed.

**Comment by taperj** [comment]
> > Is peers.dat something you want to be tracking in git? I would assume it is constantly changing and would be outside of version control? Perhaps you are doing that intentionally and seeding peers?
> 
> You are correct and I debated whether to include it or not. Really I included it because the initial installer I looked at from the APR website had included it. I went back and forth on it also, being a constantly changing file as you stated. I figured it was better to leave it included and avoid syncing problems from peers who possibly couldn't find a block source. Your point is valid and well taken though and I may cut it out of inclusion in future releases. I'd just want to do the testing to make sure it doesn't end with stuck clients unable to sync if removed.

I have just uploaded V 0.0.2 which includes removal of peers.dat from codebase and some code optimizations.
